# Generated by Django 5.0.2 on 2024-02-23 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='deatails',
            new_name='details',
        ),
    ]
